# Copy this to .streamlit/secrets.toml and fill in to run against Snowflake (optional)
[snowflake]
account = "your-account"
user = "your-username"
password = "your-password"
role = "ANALYST"
warehouse = "COMPUTE_WH"
database = "ANALYTICS"
schema = "PUBLIC"
